name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: notes-compile
          version: "Nvim 0.8.0"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto generate docs"
          branch: ${{ github.head_ref }}
